# SwiftLint configuration for LotusKey
# Following project.md conventions

# Paths to include
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - .build
  - DerivedData
  - Packages

# Rules configuration
disabled_rules:
  - trailing_whitespace
  - line_length  # Handled by file_length and type_body_length
  - switch_case_on_newline  # Too noisy for large switch statements
  - number_separator  # Not critical for small numbers

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_count
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - x
    - y

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true
  excluded:
    - Tests

type_body_length:
  warning: 300
  error: 500
  excluded:
    - Tests

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

vertical_whitespace:
  max_empty_lines: 2

trailing_comma:
  mandatory_comma: true

# Custom rules
custom_rules:
  # Prefer let over var when possible (reminder, not enforced)
  prefer_let_reminder:
    name: "Prefer let"
    regex: '^\s*var\s+\w+\s*:\s*\w+\s*$'
    message: "Consider using 'let' if this variable is not mutated"
    severity: warning

  # Avoid force unwrapping in production code
  no_force_unwrap:
    name: "Force Unwrap"
    regex: '\w+!'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping. Use optional binding or nil coalescing."
    severity: warning

  # Avoid Any type
  avoid_any_type:
    name: "Avoid Any"
    regex: '\bAny\b'
    message: "Prefer specific types over Any for type safety."
    severity: warning

# Reporter type
reporter: "xcode"
